// showcase/vue-showcase/src/components/other-components/OtherComponents.vue
<script setup lang="ts">
import {
  DbLinklist,
  DbLink,
  DbNotifications,
  DbNotification,
  DbIcon,
  DbButton
} from '@db-ui/v-elements-enterprise/dist/components';

import { ref } from 'vue';

const notification = ref(false);
</script>

<style>
db-notification {
  position: fixed;
  bottom: 1rem;
  width: 50vw;
  left: 25vw;
}
</style>

<template>
  <div>
    <p>Link list:</p>
    <DbLinklist>
      <li>
        <DbLink
          href="https://github.com/db-ui/elements/"
          target="_blank"
        >
          DB UI Elements components documentation
        </DbLink>
      </li>
      <li>
        <DbLink
          href="https://github.com/db-ui/core/"
          target="_blank"
        >
          DB UI Core components documentation
        </DbLink>
      </li>
    </DbLinklist>
    <p>Notification:</p>
    <DbButton variant="primary" @click="notification = true">
      Open Notification!
    </DbButton>
    <DbNotifications v-if="notification" variant="hovering">
      <DbNotification type="success">
        <DbIcon icon="account" slot="prenotification" variant="20-outline" />
        success: Lorem ipsum dolor sit amet, consectetur adipisicing elit
        <DbIcon
          icon="close"
          slot="postnotification"
          variant="20-outline"
          @click="notification = false"
          @keypress="notification = false"
          tabindex="0"
          role="button"
        />
      </DbNotification>
    </DbNotifications>
  </div>
</template>

// showcase/angular-showcase/src/app/components/other-components/other-components.component.ts
import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-other-components',
  templateUrl: './other-components.component.html',
  styleUrls: ['other-components.component.css']
})
export class OtherComponentsComponent {
  notification: boolean;
}

<div>
  <p>Link list:</p>
  <db-linklist>
    <li>
      <db-link
        href="https://github.com/db-ui/elements/"
        target="_blank"
      >
        DB UI Elements components documentation
      </db-link>
    </li>
    <li>
      <db-link
        href="https://github.com/db-ui/core/"
        target="_blank"
      >
        DB UI Core components documentation
      </db-link>
    </li>
  </db-linklist>
  <p>Notification:</p>
  <db-button variant="primary" (click)="notification = true">
    Open Notification!
  </db-button>
  <db-notifications *ngIf="notification" variant="hovering">
    <db-notification type="success">
      <db-icon
        icon="account"
        slot="prenotification"
        variant="20-outline"
      ></db-icon>
      success: Lorem ipsum dolor sit amet, consectetur adipisicing elit
      <db-icon
        icon="close"
        slot="postnotification"
        variant="20-outline"
        (keypress)="notification = false"
        (click)="notification = false"
        tabindex="0"
        role="button"
      ></db-icon>
    </db-notification>
  </db-notifications>
</div>
