// showcase/react-showcase/src/components/other-elements/index.jsx
import {
  DbIcon,
  DbImage,
  DbLink,
  DbLogo,
  DbProgress,
  DbTag,
  DbChip
} from '@db-ui/react-elements';

function OtherElements() {
  return (
    <div>
      <p>DbIcon:</p>
      <DbIcon icon="account" variant="32-outline" />
      <DbIcon icon="check-circle"></DbIcon>
      <p>DbProgress:</p> <DbProgress value="60" max="100" />
      <p>DbTag:</p>
      <DbTag>default</DbTag>
      <DbTag variant="informative">informative</DbTag>
      <DbTag variant="success">success</DbTag>
      <p>DbLogo:</p>
      <DbLogo></DbLogo>
      <p>DbChip:</p>
      <DbChip interactiontype="filter" icon="account">
        default
      </DbChip>
      <DbChip
        interactiontype="filter"
        iconafter="account"
        variant="informative"
        disabled
      >
        informative
      </DbChip>
      <DbChip
        interactiontype="filter"
        icon="account"
        iconafter="account"
        variant="success"
      >
        success
      </DbChip>
      <p>DbImage:</p>
      <DbImage
        alt="DB Image alternative text"
        src="https://db-ui.github.io/core/samples/images/maximilian--UZa949e8LE-unsplash.376x282.squoosh.mozjpeg.jpg"
        width="376"
        height="253"
      />
      <p>DbLink:</p>
      <DbLink href="https://github.com/db-ui/elements/" target="_blank">
        DB UI Elements components documentation
      </DbLink>
    </div>
  );
}

export default OtherElements;

// showcase/angular-showcase/src/app/components/other-elements/other-elements.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-other-elements',
  templateUrl: './other-elements.component.html'
})
export class OtherElementsComponent {}

<div>
  <p>DbIcon:</p>
  <db-icon icon="account" variant="32-outline"></db-icon>
  <p>DbProgress:</p>
  <db-progress value="60" max="100"></db-progress>
  <p>DbTag:</p>
  <db-tag>default</db-tag>
  <db-tag variant="informative">informative</db-tag>
  <db-tag variant="success">success</db-tag>
  <p>DbChip:</p>
  <db-chip interactiontype="filter" icon="account">default</db-chip>
  <db-chip
    interactiontype="filter"
    iconafter="account"
    variant="informative"
    disabled
    >informative</db-chip
  >
  <db-chip
    interactiontype="filter"
    icon="account"
    iconafter="account"
    variant="success"
    >success</db-chip
  >
  <p>DbImage:</p>
  <db-image
    alt="DB Image alternative text"
    src="https://db-ui.github.io/core/samples/images/maximilian--UZa949e8LE-unsplash.376x282.squoosh.mozjpeg.jpg"
    width="376"
    height="253"
  ></db-image>
  <p>DbLink:</p>
  <db-link href="https://github.com/db-ui/elements/" target="_blank">
    DB UI Elements components documentation
  </db-link>
  <p>DbLogo:</p>
  <db-logo></db-logo>
</div>
