// showcase/react-showcase/src/App.jsx
import '@db-ui/core/dist/css/enterprise/db-ui-core.vars.css';
import './App.css';
import {
  DbBrand,
  DbFooter,
  DbHeader,
  DbLink,
  DbMainnavigation,
  DbPage
} from '@db-ui/react-elements';
// 👆 This is the enterprise theme, even if we do not call it like that here
import { navigationItems } from './components/navigation/items';
import { Link, Outlet } from 'react-router-dom';

function App() {
  return (
    <>
      <DbPage>
        <DbHeader slot="header">
          <DbBrand src="/db_logo.svg" href="/">
            DB UI Elements in React Showcase
          </DbBrand>
          <DbMainnavigation>
            <DbLink href="/" current="page">
              Pages
              {navigationItems.map((item, index) => (
                <DbLink
                  current={navigationItems.indexOf(item) === 0 ? 'page' : false}
                  key={`mainnavigation-item-${index}`}
                >
                  <Link to={item.link}>{item.label}</Link>
                </DbLink>
              ))}
            </DbLink>
          </DbMainnavigation>
          <div />
        </DbHeader>
        <div>
          <Outlet />
        </div>
        <DbFooter slot="footer" copyright border />
      </DbPage>
    </>
  );
}

export default App;

// showcase/angular-lts-showcase/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { isAreaCurrent, NAVIGATION_ITEMS } from './utils/navigation-item';
import {
  DbButton,
  DbCheckbox,
  DbPage,
  DbLink,
  DbHeader,
  DbMainnavigation,
  DbFooter,
  DbBrand
} from '../../../../packages/db-ui-elements-angular/projects/lib/src';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  standalone: true,

  imports: [
    ReactiveFormsModule,
    FormsModule,
    DbButton,
    DbCheckbox,
    DbPage,
    DbLink,
    DbHeader,
    DbMainnavigation,
    DbFooter,
    DbBrand,
    RouterOutlet,
    RouterLink
  ]
})
export class AppComponent implements OnInit {
  title = 'angular-lts-showcase';
  navigationItems = NAVIGATION_ITEMS;
  isAria = isAreaCurrent;

  input: string = '';
  checkbox: boolean | null = false;
  radio: string = '';
  select: string | null = '';
  textarea: string | null = '';
  toggle: boolean = false;

  checkboxControl = new FormControl<boolean>(false, { nonNullable: false });
  radioControl = new FormControl<string>('', { nonNullable: true });
  selectControl = new FormControl<string>('', { nonNullable: false });
  textareaControl = new FormControl<string>('', { nonNullable: false });

  radioButtons = ['radio-01', 'radio-02', 'radio-03'];

  ngOnInit(): void {
    this.checkboxControl.valueChanges.subscribe(
      (value) => (this.checkbox = value)
    );
    this.radioControl.valueChanges.subscribe((value) => (this.radio = value));
    this.selectControl.valueChanges.subscribe((value) => (this.select = value));
    this.textareaControl.valueChanges.subscribe(
      (value) => (this.textarea = value)
    );
  }

  showValues(): void {
    alert(
      JSON.stringify({
        input: this.input,
        checkbox: this.checkbox,
        radio: this.radio,
        select: this.select,
        textarea: this.textarea
      })
    );
  }

  logPagination(evt: CustomEvent) {
    // eslint-disable-next-line no-console
    console.log('Clicked in <db-pagination>: ', evt.detail.target.innerText);
  }
}

<db-page>
  <db-header slot="header">
    <db-brand src="./assets/db_logo.svg" href="/angular-lts-showcase">
      DB UI Elements in Angular Showcase
    </db-brand>
    <db-mainnavigation>
      <db-link href="/" current="page">
        Pages
        @for (item of navigationItems; track item; let i = $index) {
          <db-link [attr.current]="isAria(i)">
            <a [routerLink]="item.link">{{ item.label }}</a>
          </db-link>
        }
      </db-link>
    </db-mainnavigation>
    <div></div>
  </db-header>
  <div>
    <router-outlet></router-outlet>
  </div>
  <db-footer slot="footer" copyright border></db-footer>
</db-page>
