// showcase/angular-showcase/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { isAreaCurrent, NAVIGATION_ITEMS } from './utils/navigation-item';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'angular-showcase';
  navigationItems = NAVIGATION_ITEMS;
  isAria = isAreaCurrent;

  input: string;
  checkbox: boolean;
  radio: string;
  select: string;
  textarea: string;

  checkboxControl = new FormControl();
  radioControl = new FormControl();
  selectControl = new FormControl();
  textareaControl = new FormControl();

  radioButtons = ['radio-01', 'radio-02', 'radio-03'];

  ngOnInit(): void {
    this.checkboxControl.valueChanges.subscribe(
      (value) => (this.checkbox = value)
    );
    this.radioControl.valueChanges.subscribe((value) => (this.radio = value));
    this.selectControl.valueChanges.subscribe((value) => (this.select = value));
    this.textareaControl.valueChanges.subscribe(
      (value) => (this.textarea = value)
    );
  }

  showValues(): void {
    alert(
      JSON.stringify({
        input: this.input,
        checkbox: this.checkbox,
        radio: this.radio,
        select: this.select,
        textarea: this.textarea
      })
    );
  }

  logPagination(evt: CustomEvent) {
    // eslint-disable-next-line no-console
    console.log('Clicked in <db-pagination>: ', evt.detail.target.innerText);
  }
}

<db-page>
  <db-header slot="header">
    <db-brand src="./assets/db_logo.svg" href="/angular-showcase">
      DB UI Elements in Angular Showcase
    </db-brand>
    <db-mainnavigation>
      <db-link href="/" current="page">
        Pages
        <db-link
          *ngFor="let item of navigationItems; index as i"
          [attr.current]="isAria(i)"
        >
          <a [routerLink]="item.link">{{ item.label }}</a>
        </db-link>
      </db-link>
    </db-mainnavigation>
    <div></div>
  </db-header>
  <div>
    <router-outlet></router-outlet>
  </div>
  <db-footer slot="footer" copyright border></db-footer>
</db-page>

// showcase/react-showcase/src/App.jsx
import '@db-ui/core/dist/css/enterprise/db-ui-core.vars.css';
import './App.css';
import {
  DbBrand,
  DbFooter,
  DbHeader,
  DbLink,
  DbMainnavigation,
  DbPage
} from '@db-ui/react-elements';
// 👆 This is the enterprise theme, even if we do not call it like that here
import { navigationItems } from './components/navigation/items';
import { Link, Outlet } from 'react-router-dom';

function App() {
  return (
    <>
      <DbPage>
        <DbHeader slot="header">
          <DbBrand src="/db_logo.svg" href="/">
            DB UI Elements in React Showcase
          </DbBrand>
          <DbMainnavigation>
            <DbLink href="/" current="page">
              Pages
              {navigationItems.map((item, index) => (
                <DbLink
                  current={navigationItems.indexOf(item) === 0 ? 'page' : false}
                  key={`mainnavigation-item-${index}`}
                >
                  <Link to={item.link}>{item.label}</Link>
                </DbLink>
              ))}
            </DbLink>
          </DbMainnavigation>
          <div />
        </DbHeader>
        <div>
          <Outlet />
        </div>
        <DbFooter slot="footer" copyright border />
      </DbPage>
    </>
  );
}

export default App;
