// showcase/vue-showcase/src/App.vue
<script setup lang="ts">
import {
  DbBrand,
  DbFooter,
  DbHeader,
  DbPage,
  DbMainnavigation,
  DbLink
} from '@db-ui/v-elements/dist/components';
import { navigationItems } from '@/navigationItems';
</script>

<template>
  <DbPage>
    <DbHeader slot="header">
      <DbBrand src="db_logo.svg" href="/vue-showcase/">
        DB UI Elements in Vue Showcase
      </DbBrand>
      <DbMainnavigation>
        <DbLink href="/" current="page">
          Pages
          <DbLink
            v-for="item of navigationItems"
            :current.attr="
              navigationItems.indexOf(item) === 0 ? 'page' : 'false'
            "
          >
            <router-link :to="item.link">{{ item.label }}</router-link>
          </DbLink>
        </DbLink>
      </DbMainnavigation>
      <div />
    </DbHeader>
    <div><router-view></router-view></div>
    <DbFooter slot="footer" copyright border></DbFooter>
  </DbPage>
</template>

// showcase/react-showcase/src/App.jsx
import '@db-ui/core/dist/css/enterprise/db-ui-core.vars.css';
import './App.css';
import {
  DbBrand,
  DbFooter,
  DbHeader,
  DbLink,
  DbMainnavigation,
  DbPage
} from '@db-ui/react-elements';
// 👆 This is the enterprise theme, even if we do not call it like that here
import { navigationItems } from './components/navigation/items';
import { Link, Outlet } from 'react-router-dom';

function App() {
  return (
    <>
      <DbPage>
        <DbHeader slot="header">
          <DbBrand src="/db_logo.svg" href="/">
            DB UI Elements in React Showcase
          </DbBrand>
          <DbMainnavigation>
            <DbLink href="/" current="page">
              Pages
              {navigationItems.map((item, index) => (
                <DbLink
                  current={navigationItems.indexOf(item) === 0 ? 'page' : false}
                  key={`mainnavigation-item-${index}`}
                >
                  <Link to={item.link}>{item.label}</Link>
                </DbLink>
              ))}
            </DbLink>
          </DbMainnavigation>
          <div />
        </DbHeader>
        <div>
          <Outlet />
        </div>
        <DbFooter slot="footer" copyright border />
      </DbPage>
    </>
  );
}

export default App;
