// showcase/react-showcase/src/components/navigation/index.jsx
import { DbLink, DbSidenavi } from '@db-ui/react-elements';
import React from 'react';
import { navigationItems } from './items';
import { Link } from 'react-router-dom';

function Navigation() {
  return (
    <div>
      <p>DbSidenavi:</p>
      <DbSidenavi>
        {navigationItems.map((item, index) => (
          <DbLink
            current={navigationItems.indexOf(item) === 0 ? 'page' : false}
            icon={item.icon}
            key={`sidenavi-item-${index}`}
          >
            <Link to={item.link}>{item.label}</Link>
          </DbLink>
        ))}
      </DbSidenavi>
    </div>
  );
}

export default Navigation;

// showcase/angular-lts-showcase/src/app/components/navigation/navigation.component.ts
import { Component } from '@angular/core';
import { isAreaCurrent, NAVIGATION_ITEMS } from '../../utils/navigation-item';
import {
  DbLink,
  DbSidenavi
} from '../../../../../../packages/db-ui-elements-angular/projects/lib/src';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  standalone: true,
  imports: [DbSidenavi, DbLink, RouterLink]
})
export class NavigationComponent {
  navigationItems = NAVIGATION_ITEMS;
  isAria = isAreaCurrent;
}

<div>
  <p>DbSidenavi:</p>
  <db-sidenavi>
    @for (item of navigationItems; track item; let i = $index) {
      <db-link [attr.current]="isAria(i)" [attr.icon]="item.icon">
        <a [routerLink]="item.link">{{ item.label }}</a>
      </db-link>
    }
  </db-sidenavi>
</div>
