// showcase/react-showcase/src/components/navigation/index.jsx
import { DbLink, DbSidenavi } from '@db-ui/react-elements';
import React from 'react';
import { navigationItems } from './items';
import { Link } from 'react-router-dom';

function Navigation() {
  return (
    <div>
      <p>DbSidenavi:</p>
      <DbSidenavi>
        {navigationItems.map((item, index) => (
          <DbLink
            current={navigationItems.indexOf(item) === 0 ? 'page' : false}
            icon={item.icon}
            key={`sidenavi-item-${index}`}
          >
            <Link to={item.link}>{item.label}</Link>
          </DbLink>
        ))}
      </DbSidenavi>
    </div>
  );
}

export default Navigation;

// showcase/vue-showcase/src/components/navigation/Navigation.vue
<script setup lang="ts">
import { DbSidenavi, DbLink } from '@db-ui/v-elements/dist/components';

import { navigationItems } from '@/navigationItems';
</script>

<template>
  <div>
    <p>DbSidenavi:</p>
    <DbSidenavi>
      <DbLink
        v-for="item in navigationItems"
        :key="item.link"
        :icon.attr="item.icon"
        :current.attr="navigationItems.indexOf(item) === 0 ? 'page' : 'false'"
      >
        <router-link :to="item.link">{{ item.label }}</router-link>
      </DbLink>
    </DbSidenavi>
  </div>
</template>
