// showcase/react-showcase/src/components/tab-bar/index.jsx
import Form from '../form';
import OtherElements from '../other-elements';
import OtherComponents from '../other-components';
import Tables from '../tables';
import { DbTab, DbTabBar } from '@db-ui/react-elements';
import Navigation from '../navigation';

function TabBar() {
  return (
    <DbTabBar>
      <DbTab label="Inputs" name="tab-bar" active>
        <Form />
      </DbTab>
      <DbTab label="Other Elements" name="tab-bar">
        <OtherElements />
      </DbTab>
      <DbTab label="Other Components" name="tab-bar">
        <OtherComponents />
      </DbTab>
      <DbTab label="Tables" name="tab-bar">
        <Tables />
      </DbTab>
      <DbTab label="Navigation" name="tab-bar">
        <Navigation />
      </DbTab>
    </DbTabBar>
  );
}

export default TabBar;

// showcase/angular-lts-showcase/src/app/components/tab-bar/tab-bar.component.ts
import { Component } from '@angular/core';
import {
  DbTab,
  DbTabBar
} from '../../../../../../packages/db-ui-elements-angular/projects/lib/src';
import { FormComponent } from '../form/form.component';
import { OtherElementsComponent } from '../other-elements/other-elements.component';
import { OtherComponentsComponent } from '../other-components/other-components.component';
import { TablesComponent } from '../tables/tables.component';
import { NavigationComponent } from '../navigation/navigation.component';

@Component({
  selector: 'app-tab-bar',
  templateUrl: './tab-bar.component.html',
  standalone: true,
  imports: [
    DbTabBar,
    DbTab,
    FormComponent,
    OtherElementsComponent,
    OtherComponentsComponent,
    TablesComponent,
    NavigationComponent
  ]
})
export class TabBarComponent {}
