// showcase/vue-showcase/src/components/form/Form.vue
<script setup lang="ts">
import {
  DbButton,
  DbCheckbox,
  DbInput,
  DbRadio,
  DbSelect,
  DbTextarea,
  DbToggle
} from '@db-ui/v-elements/dist/components';

import { ref } from 'vue';

const input = ref('');
const checkbox = ref(false);
const textarea = ref('');
const select = ref('');
const radio = ref('');
const toggle = ref(false);

const logAll = () => {
  alert(
    JSON.stringify({
      input: input.value,
      checkbox: !!checkbox.value,
      radio: radio.value,
      select: select.value,
      textarea: textarea.value,
      toggle: toggle.value
    })
  );
};
</script>

<style>
.form-container {
  display: flex;
}

.form-container fieldset {
  display: flex;
  flex-direction: column;
  margin: 0 8px;
  width: 50%;

  /* Disabling fieldset styles in this specific case */
  padding: 0;
  border-color: transparent;
}
</style>

<template>
  <div>
    <div class="form-container">
      <fieldset>
        <form>
          <p>DbInput:</p>
          <DbInput
            label="Infield"
            name="input-name"
            v-model="input"
            className="fullWidth"
          />
          <p>DbCheckbox:</p>
          <DbCheckbox
            label="Checkbox"
            name="checkbox-name"
            v-model="checkbox"
          />
          <p>DbRadio:</p>
          <ol>
            <li>
              <DbRadio
                label="Radio 01"
                name="radio-name"
                value="radio-01"
                v-model="radio"
              />
            </li>
            <li>
              <DbRadio
                label="Radio 02"
                name="radio-name"
                value="radio-02"
                v-model="radio"
              />
            </li>
            <li>
              <DbRadio
                label="Radio 03"
                name="radio-name"
                value="radio-03"
                v-model="radio"
              />
            </li>
          </ol>
          <p>DbSelect:</p>
          <DbSelect label="Selectbox" name="select-name" v-model="select">
            <option selected>Option 1</option>
            <option>Option 2</option>
            <option>Option 3</option>
          </DbSelect>
          <p>DbTextarea:</p>
          <DbTextarea
            label="Textarea"
            name="textarea-name"
            v-model="textarea"
          />
          <p>DbToggle:</p>
          <DbToggle v-model="toggle" />
        </form>
      </fieldset>
      <fieldset>
        <p>DbButton:</p>
        <DbButton variant="primary" @click="logAll()">
          Hi from Showcase!
        </DbButton>
        <h2>Output</h2>
        <dl>
          <dt>inputs value</dt>
          <dd>{{ input ? input : 'No Input set' }}</dd>
          <dt>checkbox</dt>
          <dd>{{ checkbox ? 'yes' : 'no' }}</dd>
          <dt>radio</dt>
          <dd>{{ radio ? radio : 'No radio selected' }}</dd>
          <dt>select</dt>
          <dd>{{ select ? select : 'Not Selected' }}</dd>
          <dt>textarea</dt>
          <dd>{{ textarea ? textarea : 'No Text set' }}</dd>
          <dt>toggle</dt>
          <dd>{{ toggle.toString() }}</dd>
        </dl>
      </fieldset>
    </div>
  </div>
</template>

// showcase/react-showcase/src/components/form/index.js
import { useState } from 'react';
import {
  DbButton,
  DbCheckbox,
  DbInput,
  DbRadio,
  DbSelect,
  DbTextarea,
  DbToggle
} from '@db-ui/react-elements';

import './form.css';

function Form() {
  const [input, setInput] = useState('');
  const [checkbox, setCheckbox] = useState(false);
  const [radio, setRadio] = useState('');
  const [select, setSelect] = useState('');
  const [textarea, setTextarea] = useState('');
  const [toggle, setToggle] = useState(false);

  return (
    <div>
      <div className="form-container">
        <fieldset>
          <form>
            <p>DbInput:</p>
            <DbInput
              label="Infield"
              name="input-name"
              onInput={(event) => setInput(event.target.value)}
              className="fullWidth"
            />
            <p>DbCheckbox:</p>
            <DbCheckbox
              label="Checkbox"
              name="checkbox-name"
              onInput={(event) => setCheckbox(event.target.checked)}
            />
            <p>DbRadio:</p>
            <ol>
              <li>
                <DbRadio
                  label="Radio 01"
                  name="radio-name"
                  value="Radio 01"
                  onInput={(event) => setRadio(event.target.value)}
                />
              </li>
              <li>
                <DbRadio
                  label="Radio 02"
                  name="radio-name"
                  value="Radio 02"
                  onInput={(event) => setRadio(event.target.value)}
                />
              </li>
              <li>
                <DbRadio
                  label="Radio 03"
                  name="radio-name"
                  value="Radio 03"
                  onInput={(event) => setRadio(event.target.value)}
                />
              </li>
            </ol>
            <p>DbSelect:</p>
            <DbSelect
              label="Selectbox"
              name="select-name"
              onInput={(event) => setSelect(event.target.value)}
            >
              <option selected>Option 1</option>
              <option>Option 2</option>
              <option>Option 3</option>
            </DbSelect>
            <p>DbTextarea:</p>
            <DbTextarea
              label="Textarea"
              name="textarea-name"
              onInput={(event) => {
                setTextarea(event.target.value);
              }}
            />
            <p>DbToggle:</p>
            <DbToggle
              onInput={() => {
                setToggle(!toggle);
              }}
            />
          </form>
        </fieldset>
        <fieldset>
          <p>DbButton:</p>
          <DbButton
            variant="primary"
            onClick={(_) => {
              return alert(
                JSON.stringify({
                  input: input,
                  checkbox: checkbox,
                  radio: radio,
                  select: select,
                  textarea: textarea,
                  toggle: toggle
                })
              );
            }}
          >
            Hi from Showcase!
          </DbButton>
          <h2>Output</h2>
          <dl>
            <dt>inputs value</dt>
            <dd>{input ? input : 'No Input set'}</dd>
            <dt>checkbox</dt>
            <dd>{checkbox ? 'yes' : 'no'}</dd>
            <dt>radio</dt>
            <dd>{radio ? radio : 'No radio selected'}</dd>
            <dt>select</dt>
            <dd>{select ? select : 'Not Selected'}</dd>
            <dt>textarea</dt>
            <dd>{textarea ? textarea : 'No Text set'}</dd>
            <dt>toggle</dt>
            <dd>{toggle.toString()}</dd>
          </dl>
        </fieldset>
      </div>
    </div>
  );
}
export default Form;
