// showcase/angular-showcase/src/app/components/navigation/navigation.component.ts
import { Component } from '@angular/core';
import { isAreaCurrent, NAVIGATION_ITEMS } from '../../utils/navigation-item';

@Component({
  standalone: false,
  selector: 'app-navigation',
  templateUrl: './navigation.component.html'
})
export class NavigationComponent {
  navigationItems = NAVIGATION_ITEMS;
  isAria = isAreaCurrent;
}

<div>
  <p>DbSidenavi:</p>
  <db-sidenavi>
    <db-link
      *ngFor="let item of navigationItems; index as i"
      [attr.current]="isAria(i)"
      [attr.icon]="item.icon"
    >
      <a [routerLink]="item.link">{{ item.label }}</a>
    </db-link>
  </db-sidenavi>
</div>

// showcase/react-showcase/src/components/navigation/index.jsx
import { DbLink, DbSidenavi } from '@db-ui/react-elements';
import React from 'react';
import { navigationItems } from './items';
import { Link } from 'react-router-dom';

function Navigation() {
  return (
    <div>
      <p>DbSidenavi:</p>
      <DbSidenavi>
        {navigationItems.map((item, index) => (
          <DbLink
            current={navigationItems.indexOf(item) === 0 ? 'page' : false}
            icon={item.icon}
            key={`sidenavi-item-${index}`}
          >
            <Link to={item.link}>{item.label}</Link>
          </DbLink>
        ))}
      </DbSidenavi>
    </div>
  );
}

export default Navigation;
